apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: servershop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql/data  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: servershop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi